### PR TITLE
Add support for pharo 9 using the headless latest vm

### PR DESCRIPTION
**Pull request by tesonep**

### CODE REVIEW

**Comment by gcotelli** [comment]
@serpi90 I will let the review to you. Do we need to change something in docker hub also?

**Comment by serpi90** [comment]
> @serpi90 I will let the review to you. Do we need to change something in docker hub also?

I'll do some local tests and review.
Yes, a new build must be configured in dockerhub: https://hub.docker.com/repository/docker/basmalltalk/pharo/builds/edit i've granted you access.

**Review by serpi90 — APPROVED** [review]
:+1:

**Comment by gcotelli** [comment]
Thanks @tesonep

**Pull request merged**
